import { useState } from 'react'
import { useTheme } from '../../contexts/ThemeContext'
import PageHeader from '../../components/ui/PageHeader'
const TABS=['Height & Weight','Vision','Hearing','General','Rejections','Prep Tips']
export default function MedicalStandards() {
  const { theme }=useTheme(); const [tab,setTab]=useState(0)
  return (
    <div className="p-4 md:p-6 max-w-3xl mx-auto">
      <PageHeader title="MEDICAL STANDARDS" subtitle="NDA medical requirements — know before you go." icon="🏥" page="Medical Standards" image="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800"/>
      <div className="flex gap-2 flex-wrap mb-5">{TABS.map((t,i)=><button key={i} onClick={()=>setTab(i)} className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${tab===i?'text-[#0B1628] font-bold':'text-gray-400 border'}`} style={tab===i?{background:`linear-gradient(135deg,${theme.accent},#E8C96A)`}:{borderColor:theme.border}}>{t}</button>)}</div>
      {tab===0&&<div><div className="grid grid-cols-3 gap-3 mb-4">{[{l:'Army Male',v:'157cm'},{l:'Navy/AF Male',v:'162.5cm'},{l:'Female (all)',v:'152cm'}].map(s=><div key={s.l} className="text-center rounded-xl p-3 border" style={{background:theme.bgMid,borderColor:theme.border}}><p className="font-bebas text-xl" style={{color:theme.accent}}>{s.v}</p><p className="text-[10px] text-gray-400">{s.l}</p></div>)}</div>
      <div className="overflow-x-auto rounded-xl border" style={{borderColor:theme.border}}><table className="w-full text-xs"><thead style={{background:theme.bgLight}}><tr>{['Height','Min Wt','Max Wt','Status'].map(h=><th key={h} className="px-3 py-2 text-left font-mono text-gray-400">{h}</th>)}</tr></thead><tbody>{[[152,42,54],[155,44,57],[157,46,59],[160,48,61],[163,50,64],[165,52,66],[168,54,69],[170,56,71],[173,58,74],[175,60,77],[178,62,80],[180,65,83]].map(([h,mn,mx])=><tr key={h} className="border-t" style={{borderColor:theme.border}}><td className="px-3 py-2 text-gray-300">{h}cm</td><td className="px-3 py-2 text-gray-300">{mn}kg</td><td className="px-3 py-2 text-gray-300">{mx}kg</td><td className="px-3 py-2 text-green-400">✓</td></tr>)}</tbody></table></div></div>}
      {tab===1&&<div className="space-y-3">{[{s:'Army',b:'6/6 or 6/9',w:'6/36',g:'Allowed (max ±3.5D)'},{s:'Navy',b:'6/6 or 6/9',w:'6/18',g:'Not allowed'},{s:'Air Force',b:'6/6',w:'6/6',g:'NOT allowed'}].map(v=><div key={v.s} className="px-4 py-3 rounded-xl border" style={{background:theme.bgMid,borderColor:theme.border}}><p className="font-bebas text-lg" style={{color:theme.accent}}>{v.s}</p><p className="text-xs text-gray-400">Better Eye: {v.b} · Worse Eye: {v.w} · Glasses: {v.g}</p></div>)}</div>}
      {tab===4&&<div className="space-y-2">{[['👁️ Poor Eyesight','High myopia above ±3.5D. Most common rejection.'],['⚖️ Weight Issues','Not fitting height-weight chart.'],['🦶 Flat Foot','Grade II or III. Get checked early.'],['🦷 Dental Issues','Decayed teeth = deferment. Visit dentist.'],['🩸 High BP','No caffeine before medical. Stay calm.'],['🎨 Visible Tattoo','On hands, neck or face area.']].map(([t,d],i)=><div key={i} className="flex gap-3 px-4 py-3 rounded-xl border" style={{background:theme.bgMid,borderColor:theme.border}}><span className="text-lg">{t.split(' ')[0]}</span><div><p className="text-sm text-white font-medium">{t.slice(3)}</p><p className="text-xs text-gray-400">{d}</p></div></div>)}</div>}
      {tab===5&&<div className="space-y-3">{[{t:'6 Months Before',items:['Full medical checkup','Check eyesight power','Start BMI correction','Fix flat foot if needed','Visit dentist']},{t:'Day of Medical',items:['No caffeine','Eat light breakfast','Arrive early','Declare all history honestly','Stay calm']}].map(s=><div key={s.t} className="rounded-xl p-4 border" style={{background:theme.bgMid,borderColor:theme.border}}><p className="font-bebas text-lg mb-2" style={{color:theme.accent}}>{s.t}</p>{s.items.map((item,i)=><p key={i} className="text-sm text-gray-300 flex gap-2"><span style={{color:theme.accent}}>•</span>{item}</p>)}</div>)}</div>}
    </div>
  )
}